"""
Resolver service for generating auto-resolutions using Gemini API.
"""
import os
import requests
from app.schemas.ticket import ResolutionOutput


class ResolverService:
    """Service for generating ticket resolutions using Gemini Pro API."""

    def __init__(self):
        """Initialize with Gemini API key."""
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

    def generate_resolution(
        self,
        title: str,
        description: str,
        category: str,
        priority: str
    ) -> ResolutionOutput:
        """
        Generate a resolution for a ticket using Gemini API.

        Args:
            title: Ticket title
            description: Ticket description
            category: Ticket category
            priority: Ticket priority

        Returns:
            ResolutionOutput with resolution text and explanation

        Raises:
            ValueError: If API call fails
        """
        if not self.api_key:
            return self._get_mock_resolution(title, description, category)

        prompt = self._build_prompt(title, description, category, priority)

        try:
            response = requests.post(
                self.base_url,
                params={"key": self.api_key},
                json={"contents": [{"parts": [{"text": prompt}]}]},
                timeout=10
            )
            response.raise_for_status()

            result = response.json()

            # Extract text from Gemini response
            if "candidates" in result and len(result["candidates"]) > 0:
                resolution_text = result["candidates"][0]["content"]["parts"][0]["text"]
                return ResolutionOutput(
                    resolution=resolution_text,
                    explanation="Generated by Gemini AI based on ticket details"
                )

            raise ValueError("Invalid Gemini API response structure")

        except requests.exceptions.RequestException as e:
            print(f"Gemini API error: {e}. Using mock resolution.")
            return self._get_mock_resolution(title, description, category)

    def _build_prompt(
        self,
        title: str,
        description: str,
        category: str,
        priority: str
    ) -> str:
        """Build the resolution generation prompt."""
        return f"""You are a helpful support agent. Generate a concise, actionable resolution for this support ticket.

Ticket Title: {title}
Ticket Description: {description}
Category: {category}
Priority: {priority}

Provide a brief, professional resolution (2-3 sentences max) that addresses the issue.
Use markdown formatting if helpful (bullet points, bold for emphasis).
Focus on actionable steps the user can take or what you'll do to resolve it.
"""

    def _get_mock_resolution(
        self,
        title: str,
        description: str,
        category: str
    ) -> ResolutionOutput:
        """Generate mock resolution based on category."""

        resolutions = {
            "auth": "We've securely reset your account password and cleared all active sessions. Please log in with the temporary password sent to your registered email. If you still can't access your account, please verify your email address is correct.",
            "billing": "We've reviewed your invoice and identified the billing discrepancy. A refund has been processed for the duplicate charge and will appear in your account within 3-5 business days. Thank you for bringing this to our attention.",
            "infra": "Our infrastructure team is investigating the reported service disruption. We've identified the root cause and are implementing fixes. Expected resolution time is 2 hours. We'll provide updates every 30 minutes.",
            "ui": "Thank you for the bug report. We've identified the issue with the submit button on Safari. A fix has been deployed and should take effect within the next few minutes. Please clear your browser cache and try again.",
            "api": "We've identified the issue causing 500 errors on the /api/users endpoint. Our engineers are deploying a fix now. The API should be restored within 15 minutes. Thank you for your patience."
        }

        resolution = resolutions.get(
            category.lower(),
            "We're working on your issue and will provide an update shortly. Thank you for your patience."
        )

        return ResolutionOutput(
            resolution=resolution,
            explanation="Generated based on ticket category and common patterns"
        )
